version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Pre-build steps...
      - npm run build

  build:
    commands:
      - echo Building the project...
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: 'build' # or the directory where your build outputs to

cache:
  paths:
    - 'node_modules/**/*'


